name: result
version: 0.1.0
description: Result Type for Dart.
repository: https://github.com/veloce/result

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  http: ^0.13.5
  test: ^1.21.4
